### ISSUE TITLE
Wrong QR code with id=0

### ISSUE THREAD

**Issue by topstone** [CatalystIT-AU/moodle-local_qrlinks#9]
QR Links always display wrong QR code with id=0, such as "http://our.moodle.site/local/qrlinks/in.php?id=0".

**Comment by topstone** [comment]
Here is my pull request:

https://github.com/CatalystIT-AU/moodle-local_qrlinks/pull/10

**Comment by brendanheywood** [comment]
Thanks @topstone,

I've fixed this but rewritten it to use the moodle_url api for the params instead of your PR

**Comment by topstone** [comment]
Thanks!
